title: ICS Study Hub
description: Organization that works on Study Buddy website
google_analytics:
show_downloads: false
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: https://ics-study-hub.github.io/
gems:
  - jekyll-mentions
